name: myworkflow
#run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main
jobs:
  linting:
    name: run linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # ESLint and Prettier must be in `package.json`
      - name: Prepare to npm ci
        run: npm install
      - name: Install Node.js dependencies
        run: npm ci

      - name: Code Linting
        run: npm run lint

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
